Updates in quickquasars to reproduce actual redshift and magnitude distribution as obtained in SV for DESIY5 mocks.
desihub/desisim pull request #569
Opened 2022-10-05 16:46 UTC by HiramHerrera

This PR adds an option to quickquasars `--dn_dzdm` which expects a 2D table with number of quasars by square degree by redshift and r-band magnitude bins.  A default file was added: `$DESISIM/py/desisim/data/dn_dzdM_EDR.fits` which contains the expected distribution for Y5 based on SV results.

The procedure of this option goes as follows:

1. Downsampling of quasars by each redshift bin to the number in the table given marginalized over magnitudes.
2. Random assignation of r-band magnitude following a PDF obtained from dividing the number of quasars for each magnitude bin for a given redshift bin divided by the total quasars in such redshift bin.

This PR also modifies the option `--extinction` by moving its position in the `quickquasars` code, and by adding an option that rescales flux in order to mantain the magnitude distribution from the previous file.

2022-10-07 11:10 UTC, andreufont commented on py/desisim/scripts/quickquasars.py
> +            if downsampling_bin<1:
We might want to add a warning, or even crash, if the required downsampling is larger than 1.

2022-10-07 11:12 UTC, andreufont commented on py/desisim/scripts/quickquasars.py
> +        log.info("Dust extinction added")
I don't know the details about this extinsion corrections, but I guess you have cross-checked this works?

2022-10-07 11:14 UTC, andreufont requested changes
@HiramHerrera - thanks for putting together this PR. Could you also add a plot or two of the luminosity function used? It might be useful to have this together with the PR. I only asked for one change, and it is to add a warning or an error when the downsampling is requested to be larger than 1, we do not want this to silently happen without us noticing.

2022-10-07 11:15 UTC, andreufont commented
There were a couple of code blocks that I didn't inspect carefully, since they use functions that I'm not familiar with. Have others reviewed this? Are these new mocks much different than the previous once, in terms of quasar luminosities?

2022-10-25 14:36 UTC, andreufont approved these changes

2022-10-25 16:29 UTC, alxogm commented
The test that is failing is unrelated with this PR and desicode, it seems to be related with Hiram making the PR from within a fork. @sbailey are you ok with us merging this branch with this one test failing?

2022-10-25 16:34 UTC, sbailey commented
@alxogm yes, that is fine.  I'll let you do the actual merge when you are ready.

2022-10-25 16:40 UTC, merged