Updated emission lines and continuum models
desihub/desisim pull request #572
Opened 2022-11-07 17:53 UTC by HiramHerrera

The following Pull Request updates:

-  `BossDr9_fiducial_continuum` model dispersions based on the results found by Rodrigo in slide 6 of [this presentation](https://desi.lbl.gov/trac/attachment/wiki/LyafMeetings/min21-03-23/Realism_QSO_template_2021_03_23.pdf) to reproduce eBOSS DR16 QSO dispersion found by PCA method.

- Emission line model, in order to better reproduce the results of PICCA Mean Flux on EDR data. 

| LyA Region       | LyB region       |
| -------------- | -------------- |
| <img width="615" alt="image" src="https://user-images.githubusercontent.com/22553137/200377271-7625aac6-6567-4288-b52a-307c92f6c57b.png"/>  | <img width="615" alt="image" src="https://user-images.githubusercontent.com/22553137/200377321-f4528718-a017-48ff-a8a5-591836a77c76.png"/> |

This new model also addresses the correlation between CIV Equivalent Width and Magnitude as found on observational data. Previous mocks didn't have such correlation
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/22553137/200379750-0dc9d7d5-7f2c-4057-8f4a-6044dfd276c8.png">

2022-11-07 18:21 UTC, alxogm requested changes

2022-11-07 18:21 UTC, alxogm commented on py/desisim/scripts/lya_simqso_model.py
> +    #kwargs['EmissionLineTrendFilename']=resource_filename('desisim', 'data/emlinetrends_Harris2016mod')
Please remove these commented lines, its not necessary to keep them

2022-11-07 18:21 UTC, alxogm commented on py/desisim/scripts/lya_simqso_model.py
> +    kwargs['EmissionLineTrendFilename']=resource_filename('desisim', 'data/emlinetrends_EDRv2')
Maybe  we should call the file emlinetrends_Harris2016mod_v2, as this new file is a modified version of the previous one.

2022-11-08 10:22 UTC, andreufont commented
Happy to merge once Alma is happy, she know more than I do about this part of the code.

I wouldn't worry too much about the "mean continuum" plot above, since the data has redshift errors that are not present in the mocks (are they?), and as we saw in Youles et al. (2022) this has an effect in the mean continuum measured by Picca.

2022-11-08 17:37 UTC, alxogm approved these changes

2022-11-08 17:37 UTC, alxogm commented
I think you can merge @HiramHerrera

2022-11-10 15:32 UTC, merged